{
 "title": "Sock-Shop Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(request_duration_seconds_count{endpoint=\"web\"}, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(request_duration_seconds_count{namespace=\"$namespace\", endpoint=\"web\"}, container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(request_duration_seconds_count{namespace=\"$namespace\", service=\"$service\", endpoint=\"web\"}, pod)"
    }
   },
   { "name": "AvgOver", "query": "1m,5m,10m,30m,60m" },
   { "name": "percentile", "query": "50,75,90,95,99" }
  ]
 },
 "panels": [
  {
   "title": "SERVICE REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "SUM by (container, method) (rate(request_duration_seconds_count{namespace=\"$namespace\", container=\"$service\", endpoint=\"web\", route!~\"health|metrics\"}[$AvgOver]))",
     "legendFormat": "{{container}}-{{method}}"
    }
   ]
  },
  {
   "title": "SERVICE FAILURE RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "SUM by (container, method, status_code) (rate(request_duration_seconds_count{namespace=\"$namespace\", container=\"$service\", status_code=~\"[4|5].*\", endpoint=\"web\", route!~\"health|metrics\"}[$AvgOver]))",
     "legendFormat": "{{container}}-{{method}}-{{status_code}}"
    }
   ]
  },
  {
   "title": "SERVICE RESPONSE TIME (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "AVG by (container, method) (rate(request_duration_seconds_sum{namespace=\"$namespace\", container=\"$service\", status_code=~\"[2|3].*\", endpoint=\"web\", route!~\"health|metrics\"}[$AvgOver]) / rate(request_duration_seconds_count{namespace=\"$namespace\", container=\"$service\", status_code=~\"[2|3].*\", endpoint=\"web\", route!~\"health|metrics\"}[$AvgOver]))",
     "legendFormat": "{{container}}-{{method}}"
    }
   ]
  },
  {
   "title": "SERVICE RESPONSE TIME (PERCENTILE)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(($percentile/100), sum(rate(request_duration_seconds_bucket{namespace=\"$namespace\", container=\"$service\", status_code=~\"[2|3].*\", endpoint=\"web\", route!~\"health|metrics\"}[$AvgOver])) by (le))",
     "legendFormat": "$percentile Percentile"
    }
   ]
  },
  {
   "title": "Active Pod Count (Selected Service)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"$service\"}"
    }
   ]
  },
  {
   "title": "Pod Running Series (Selected Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_running{container=\"$service\"})",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Pod Restarts (Selected Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[5m]))",
     "legendFormat": "Pod Restarts"
    }
   ]
  },
  {
   "title": "Pod Status (Selected Service)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_running{container=\"$service\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum by (container) (kube_pod_container_status_ready{container=\"$service\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum by (container) (kube_pod_container_status_waiting{container=\"$service\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum by (container) (kube_pod_container_status_terminated{container=\"$service\"})",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Pod CPU Usage (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[$AvgOver]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum by (pod) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"})",
     "legendFormat": "CPU Requests"
    },
    {
     "expr": "sum by (pod) (cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"})",
     "legendFormat": "CPU Limit"
    }
   ]
  },
  {
   "title": "Pod CPU Throttles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_cfs_throttled_seconds_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[$AvgOver]))",
     "legendFormat": "CPU Throttles"
    }
   ]
  },
  {
   "title": "Pod Memory Usage (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[$AvgOver]))",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum by (pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"})",
     "legendFormat": "Memory Requests"
    },
    {
     "expr": "sum by (pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Pod Memory Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_failures_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[$AvgOver]))",
     "legendFormat": "Memory Failure"
    }
   ]
  },
  {
   "title": "Pod FS Throughput (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[$AvgOver]) + rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[$AvgOver])",
     "legendFormat": "Overall Throughput"
    },
    {
     "expr": "irate(container_fs_reads_bytes_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "Read Throughput"
    },
    {
     "expr": "irate(container_fs_writes_bytes_total{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "Write Throughput"
    }
   ]
  },
  {
   "title": "Pod JVM Heap Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "Heap Utilization %"
    }
   ]
  },
  {
   "title": "Pod JVM Heap Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"G1 Eden Space\"}",
     "legendFormat": "G1 Eden Space Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"G1 Eden Space\"}",
     "legendFormat": "G1 Eden Space Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"G1 Old Gen\"}",
     "legendFormat": "G1 Old Gen Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"G1 Old Gen\"}",
     "legendFormat": "G1 Old Gen Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"G1 Survivor Space\"}",
     "legendFormat": "G1 Survivor Space Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"G1 Survivor Space\"}",
     "legendFormat": "G1 Survivor Space Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"Metaspace\"}",
     "legendFormat": "Metaspace Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", pool=\"Metaspace\"}",
     "legendFormat": "Metaspace Max"
    }
   ]
  },
  {
   "title": "Young Gen GC RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", gc=\"G1 Young Generation\"}[$AvgOver]))",
     "legendFormat": "Young Gen GC Rate"
    }
   ]
  },
  {
   "title": "Old Gen GC RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", gc=\"G1 Old Generation\"}[$AvgOver]))",
     "legendFormat": "Old Gen GC Rate"
    }
   ]
  },
  {
   "title": "Young Gen GC Time (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "AVG by (pod) \n(rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", gc=\"G1 Young Generation\"}[$AvgOver]) / rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", gc=\"G1 Young Generation\"}[$AvgOver]))",
     "legendFormat": "Young Gen GC Time"
    }
   ]
  },
  {
   "title": "Young Gen GC Time (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "AVG by (pod) \n(rate(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", gc=\"G1 Old Generation\"}[$AvgOver]) / rate(jvm_gc_collection_seconds_count{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", gc=\"G1 Old Generation\"}[$AvgOver]))",
     "legendFormat": "Old Gen GC Time"
    }
   ]
  },
  {
   "title": "Pod JVM Non Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{namespace=\"$namespace\", container=\"$service\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "Non Heap Usage"
    }
   ]
  }
 ]
}